name: Uni docker lab exercise

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/${{ vars.GHCR_USERNAME }}/${{ github.event.repository.name }}
  CACHE_REPO: docker.io/${{ vars.DOCKERHUB_USERNAME }}/build-cache

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the source_repo
        uses: actions/checkout@v4

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image with multi-arch and cache
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          outputs: type=image
          cache-from: type=registry,ref=${{ env.CACHE_REPO }}
          cache-to: type=registry,ref=${{ env.CACHE_REPO }},mode=max
          tags: ${{ env.CACHE_REPO }}

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@0.18.0
        with:
          image-ref: ${{ env.CACHE_REPO }}:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Push image to GHCR (only if no CRITICAL/HIGH CVEs)
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.CACHE_REPO }}:buildcache
          cache-to: type=registry,ref=${{ env.CACHE_REPO }}:buildcache,mode=max
